export default {
  lisa: {
    name: "Lisa Natsumi",
    title: "Engineer @Upstash",
    image_url: "blog/authors/pp-lisa.jpg",
  },
  enes: {
    name: "Enes Akar",
    title: "Cofounder @Upstash",
    url: "https://twitter.com/enesakar",
    image_url: "blog/authors/enes.png",
  },
  noah: {
    name: "Noah Fischer",
    title: "DevRel @Upstash",
    url: "https://twitter.com/noahfschr",
    image_url: "blog/authors/noah.jpg",
  },
  mehmet: {
    name: "Mehmet Dogan",
    title: "CTO @Upstash",
    url: "https://twitter.com/mmdogan",
    image_url: "blog/authors/mehmet.jpg",
  },
  sancar: {
    name: "Sancar Koyunlu",
    title: "Senior Software Engineer @Upstash",
    image_url: "blog/authors/sancar.jpg",
  },
  geoff: {
    name: "Geoff Rich",
    title: " Svelte core team member (Guest Author)",
    url: "https://geoffrich.net/",
    image_url: "blog/authors/geoff.jpg",
  },
  rosius: {
    name: "Rosius Ndimofor",
    title: "AWS Serverless Hero (Guest Author)",
    url: "https://twitter.com/atehrosius",
    image_url: "blog/authors/rosius.png",
  },
  krutie: {
    name: "Krutie Patel",
    title: "NuxtJS Ambassador (Guest Author)",
    url: "https://mobile.twitter.com/KrutiePatel",
    image_url: "blog/authors/krutie.jpeg",
  },
  omer: {
    name: "Omer Aytac",
    title: "Full Stack Developer (Guest Author)",
    url: "https://mobile.twitter.com/OmerAytac_",
    image_url: "blog/authors/omer.png",
  },
  leigh: {
    name: "Leigh Halliday",
    title: "Senior Engineering Manager, Wrapbook (Guest Author)",
    url: "https://www.youtube.com/user/leighhalliday",
    image_url: "blog/authors/leigh.png",
  },
  gabriel: {
    name: "Gabriel Guy",
    title: "Head of Product, Applicaster (Guest Author)",
    url: "https://twitter.com/gavriguy",
    image_url: "blog/authors/gabriel.png",
  },
  sonke: {
    name: "Sönke Peters",
    title: "Full Stack Web Developer (Guest Author)",
    url: "https://www.soenkep.com/",
    image_url: "blog/authors/sonke.jpg",
  },
  kay: {
    name: "Kay Plößer",
    title: "Developer and Author (Guest Author)",
    url: "https://twitter.com/K4y1s",
    image_url: "blog/authors/kay.jpeg",
  },
  adem: {
    name: "Adem Ilter",
    title: "Designer @Upstash",
    url: "https://twitter.com/ademilter",
    image_url: "blog/authors/adem.jpg",
  },
  ilter: {
    name: "Ilter Kavlak",
    title: "Site Reliability Engineer @Upstash",
    url: "https://twitter.com/ilterkavlak",
    image_url: "blog/authors/ilter.png",
  },
  burak: {
    name: "Burak Yılmaz",
    title: "Site Reliability Engineer @Upstash",
    url: "https://github.com/yilmaz-burak",
    image_url: "blog/authors/burak.png",
  },
  andreas: {
    name: "Andreas Thomas",
    title: "Software Engineer @Upstash",
    url: "https://twitter.com/chronark_",
    image_url: "blog/authors/andreas.jpeg",
  },
  vedant: {
    name: "Vedant Atodaria",
    title: "Frontend Engineer (Guest Author)",
    url: "https://fish.solar/",
    image_url: "blog/authors/fish.jpeg",
  },
  nihan: {
    name: "Nihan Iman",
    title: "Software Developer (Guest Author)",
    image_url: "blog/authors/nihan2.png",
  },
  bobby: {
    name: "Bobby Iliev",
    title: "DevOps Engineer (Guest Author)",
    image_url: "blog/authors/bobby.jpg",
  },
  jake: {
    name: "Jake Lynch",
    title: "CTO, Fig (Guest Author)",
    image_url: "blog/authors/jake.jpg",
  },
  vladimir: {
    name: "Vladimir Mihailenco",
    title: "Uptrace Founder, Go-Redis Author",
    image_url: "blog/authors/vladimir.jpg",
  },
  rodney: {
    name: "Rodney Johnson",
    title: "Technical Content Writer",
    image_url: "blog/authors/rodney.jpg",
  },
  lorenzo: {
    name: "Lorenzo Noccioli",
    title: "Founder at popEating",
    image_url: "blog/authors/lorenzo.jpg",
  },
  lambros: {
    name: "Lambros Petrou",
    title: "Software Engineer at Datadog (Guest Author)",
    image_url: "blog/authors/lambros.jpg",
  },
  max: {
    name: "Maximilian Kaske",
    title: "Fullstack Developer (Guest Author)",
    url: "https://twitter.com/mxkaske",
    image_url: "blog/authors/max.jpg",
  },
  menelaos: {
    name: "Menelaos Kotsollaris",
    title: "Staff Software Engineer at Realtor.com (Guest Author)",
    url: "https://menelaos.dev/",
    image_url: "https://i.stack.imgur.com/QXmES.jpg?s=256&g=1",
  },
  enesozcan: {
    name: "Enes Ozcan",
    title: "Senior Software Engineer at Zapata Computing (Guest Author)",
    url: "https://github.com/enozcan",
    image_url: "blog/authors/enesozcan.png",
  },
  tudor: {
    name: "Tudor Zgîmbău",
    title: "Full-Stack Engineer (Guest Author)",
    url: "https://www.linkedin.com/in/tudor-zg%C3%AEmb%C4%83u-a85274234",
    image_url: "blog/authors/tudor.jpg",
  },
  chillyfish: {
    name: "Chillyfish",
    title: "Full-Stack Engineer (Guest Author)",
    url: "https://twitter.com/chillyfish_dev",
    image_url: "blog/authors/chillyfish.jpg",
  },
  andreaselia: {
    name: "Andreas Elia",
    title: "Full-Stack Engineer (Guest Author)",
    url: "https://twitter.com/digitalandreas",
    image_url: "blog/authors/andreaselia.jpeg",
  },
  bilaltahir: {
    name: "Bilal Tahir",
    title: "Front-end developer (Guest Author)",
    url: "https://twitter.com/deepwhitman",
    image_url: "blog/authors/bilaltahir.jpeg",
  },
  thomasCazade:{
    name:"Thomas Cazade",
    title:"Founder of fastsheet (Guest Author)",
    url:"https://twitter.com/TotomInc",
    image_url:"blog/authors/thomas_cazade.jpeg",
  },
  russTran:{
    name:"Russ Tran",
    title:"Frontend Engineer at JUST.engineer (Guest Author)",
    url:"https://twitter.com/russdevdotnet",
    image_url:"blog/authors/russ_tran.jpeg",
  },
  hosna:{
    name:"Hosna Qasmei",
    title:"Full Stack Developer (Guest Author)",
    url:"https://twitter.com/hqasmei",
    image_url:"blog/authors/hosna.jpeg",
  },
  fahreddin:{
    name:"Fahreddin Ozcan",
    title:"Full Stack Developer (Guest Author)",
    url:"https://github.com/fahreddinozcan",
    image_url:"blog/authors/fahreddin.png",
  }

};
