export default {
  lisa: {
    name: "Lisa Natsumi",
    title: "Engineer @Upstash",
    url: "https://twitter.com/enesakar",
    image_url: "https://upstash.com/blog/authors/pp-lisa.jpg",
  },
  enes: {
    name: "Enes Akar",
    title: "Cofounder @Upstash",
    url: "https://twitter.com/enesakar",
    image_url: "https://upstash.com/blog/authors/enes.png",
  },
  noah: {
    name: "Noah Fischer",
    title: "DevRel @Upstash",
    url: "https://twitter.com/noahfschr",
    image_url: "https://upstash.com/blog/authors/noah.jpg",
  },
  mehmet: {
    name: "Mehmet Dogan",
    title: "CTO @Upstash",
    url: "https://twitter.com/mmdogan",
    image_url: "https://upstash.com/blog/authors/mehmet.jpg",
  },
  sancar: {
    name: "Sancar Koyunlu",
    title: "Senior Software Engineer @Upstash",
    image_url: "https://upstash.com/blog/authors/sancar.jpg",
  },
  geoff: {
    name: "Geoff Rich",
    title: "Guest Author",
    url: "https://geoffrich.net/",
    image_url: "https://upstash.com/blog/authors/geoff.jpg",
  },
  rosius: {
    name: "Rosius Ndimofor",
    title: "AWS Serverless Hero (Guest Author)",
    url: "https://twitter.com/atehrosius",
    image_url: "https://upstash.com/blog/authors/rosius.png",
  },
  krutie: {
    name: "Krutie Patel",
    title: "NuxtJS Ambassador (Guest Author)",
    url: "https://mobile.twitter.com/KrutiePatel",
    image_url: "https://upstash.com/blog/authors/krutie.jpeg",
  },
  omer: {
    name: "Omer Aytac",
    title: "Full Stack Developer (Guest Author)",
    url: "https://mobile.twitter.com/OmerAytac_",
    image_url: "https://upstash.com/blog/authors/omer.png",
  },
  leigh: {
    name: "Leigh Halliday",
    title: "Senior Engineering Manager, Wrapbook (Guest Author)",
    url: "https://www.youtube.com/user/leighhalliday",
    image_url: "https://upstash.com/blog/authors/leigh.png",
  },
  gabriel: {
    name: "Gabriel Guy",
    title: "Head of Product, Applicaster (Guest Author)",
    url: "https://twitter.com/gavriguy",
    image_url: "https://upstash.com/blog/authors/gabriel.png",
  },
  sonke: {
    name: "Sönke Peters",
    title: "Full Stack Web Developer (Guest Author)",
    url: "https://www.soenkep.com/",
    image_url: "https://upstash.com/blog/authors/sonke.jpg",
  },
  kay: {
    name: "Kay Plößer",
    title: "Developer and Author (Guest Author)",
    url: "https://twitter.com/K4y1s",
    image_url: "https://upstash.com/blog/authors/kay.jpeg",
  },
  adem: {
    name: "Adem Ilter",
    title: "Designer @Upstash",
    url: "https://twitter.com/ademilter",
    image_url: "https://upstash.com/blog/authors/adem.jpg",
  },
  ilter: {
    name: "Ilter Kavlak",
    title: "Site Reliability Engineer @Upstash",
    url: "https://twitter.com/ilterkavlak",
    image_url: "https://upstash.com/blog/authors/ilter.png",
  },
  burak: {
    name: "Burak Yılmaz",
    title: "Site Reliability Engineer @Upstash",
    url: "https://github.com/yilmaz-burak",
    image_url: "https://upstash.com/blog/authors/burak.png",
  },
  andreas: {
    name: "Andreas Thomas",
    title: "Software Engineer @Upstash",
    url: "https://twitter.com/chronark_",
    image_url: "https://upstash.com/blog/authors/andreas.jpeg",
  },
  vedant: {
    name: "Vedant Atodaria",
    title: "Frontend Engineer (Guest Author)",
    url: "https://fish.solar/",
    image_url: "https://upstash.com/blog/authors/fish.jpeg",
  },
  nihan: {
    name: "Nihan Iman",
    title: "Software Developer (Guest Author)",
    image_url: "https://upstash.com/blog/authors/nihan2.png",
  },
  bobby: {
    name: "Bobby Iliev",
    title: "DevOps Engineer (Guest Author)",
    image_url: "https://upstash.com/blog/authors/bobby.jpg",
  },
  jake: {
    name: "Jake Lynch",
    title: "CTO, Fig (Guest Author)",
    image_url: "https://upstash.com/blog/authors/jake.jpg",
  },
  vladimir: {
    name: "Vladimir Mihailenco",
    title: "Uptrace Founder, Go-Redis Author",
    image_url: "https://upstash.com/blog/authors/vladimir.jpg",
  },
  rodney: {
    name: "Rodney Johnson",
    title: "Consultant Web Developer",
    image_url: "https://upstash.com/blog/authors/rodney.jpg",
  },
  lorenzo: {
    name: "Lorenzo Noccioli",
    title: "Founder at popEating",
    image_url: "https://upstash.com/blog/authors/lorenzo.jpg",
  },
  lambros: {
    name: "Lambros Petrou",
    title: "Software Engineer at Datadog (Guest Author)",
    image_url: "https://upstash.com/blog/authors/lambros.jpg",
  },
};
