export const SITE_URL = "https://upstash.com";

export const BANNED_TAGS = [
  "undefined",
  "upstash",
  "aws",
  "database",
  "faunadb",
  "dynamodb",
];

/**
 * Display labels for blog tags. Keys must be in normalized form
 * (lowercase, kebab-cased — see `normalizeTag` in src/utils/tags.ts).
 * Any tag not listed here falls back to CSS `capitalize` rendering,
 * which is fine for simple one-word tags like `redis` or `vercel`.
 */
export const TAG_NAMES = {
  // Companies / products
  aws: "AWS",
  "aws-lambda": "AWS Lambda",
  "aws-msk": "AWS MSK",
  qstash: "QStash",
  nextjs: "Next.js",
  "next-auth": "NextAuth",
  nextauth: "NextAuth",
  "auth.js": "Auth.js",
  fly: "Fly.io",
  "fly.io": "Fly.io",
  openai: "OpenAI",
  nestjs: "NestJS",
  sveltekit: "SvelteKit",
  nuxt: "Nuxt",
  postgresql: "PostgreSQL",
  clickhouse: "ClickHouse",
  huggingface: "HuggingFace",
  fluentbit: "FluentBit",
  cloudflare: "Cloudflare",
  "cloudflare-workers": "Cloudflare Workers",
  vercel: "Vercel",
  "vercel-edge": "Vercel Edge",
  "vercel-functions": "Vercel Functions",
  kubernetes: "Kubernetes",

  // Acronyms
  ai: "AI",
  "ai-sdk": "AI SDK",
  aisdk: "AI SDK",
  "ai-infrastructure": "AI Infrastructure",
  llm: "LLM",
  "llm-observability": "LLM Observability",
  rag: "RAG",
  sql: "SQL",
  mcp: "MCP",
  sdk: "SDK",
  cdc: "CDC",
  sre: "SRE",
  api: "API",
  cli: "CLI",
  ui: "UI",
  ux: "UX",
  rest: "REST",
  http: "HTTP",
  json: "JSON",
  kv: "KV",
  cqrs: "CQRS",
  graphql: "GraphQL",
  typescript: "TypeScript",

  // Multi-word concepts
  "react-native": "React Native",
  "edge-flags": "Edge Flags",
  "edge-computing": "Edge Computing",
  "feature-flags": "Feature Flags",
  "environment-variables": "Environment Variables",
  "data-driven": "Data Driven",
  "semantic-search": "Semantic Search",
  "semantic-cache": "Semantic Cache",
  "semantic-memory": "Semantic Memory",
  "high-availability": "High Availability",
  "distributed-tracing": "Distributed Tracing",
  "distributed-systems": "Distributed Systems",
  "event-streaming": "Event Streaming",
  "log-processing": "Log Processing",
  "scalable-architecture": "Scalable Architecture",
  "batch-processing": "Batch Processing",
  "model-context-protocol": "Model Context Protocol",
  "coding-assistants": "Coding Assistants",
  "pricing-limits": "Pricing Limits",
  "developer-tools": "Developer Tools",
  "dev-tools": "Dev Tools",
  "code-review": "Code Review",
};

export enum HOME_SECTIONS {
  HERO = "hero",
  FAST = "fast",
  SERVERLESS = "serverless",
  PRODUCTS = "products",
  PRICING = "pricing",
  OPEN_SOURCE = "open-source",
  INVESTORS = "investors",
  COMMUNITY = "community",
}

export const LETTERS = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];
