export const INVESTORS = [
  {
    name: "a16z",
    title: "",
    src: "/investors/a16z.jpg",
    url: "https://twitter.com/a16z",
  },
  {
    name: "Mango Capital",
    title: "",
    src: "/investors/mango.png",
    url: "https://www.mangocapitalinc.com",
  },
  {
    name: "Bek Ventures",
    title: "",
    src: "/investors/bek-ventures.png",
    url: "https://www.bekventures.com",
  },
  {
    name: "Guillermo Rauch",
    title: "CEO, Vercel",
    src: "/investors/rauchg.jpg",
    url: "https://twitter.com/rauchg",
  },
  {
    name: "Matias Woloski",
    title: "Founder, Auth0",
    src: "/investors/matias.png",
    url: "https://twitter.com/woloski",
  },
  {
    name: "Max Stoiber",
    title: "Creator of styled-components",
    src: "/investors/mxstbr.jpeg",
    url: "https://twitter.com/mxstbr",
  },
  {
    name: "Naval Ravikant",
    title: "Founder, AngelList",
    src: "/investors/naval.png",
    url: "https://twitter.com/naval",
  },
  {
    name: "Nuno Job",
    title: "Ground Control Ventures",
    src: "/investors/dscape.jpeg",
    url: "https://twitter.com/dscape",
  },
  {
    name: "Andreas Klinger",
    title: "Remote First Capital",
    src: "/investors/andreas-klinger.jpeg",
    url: "https://twitter.com/andreasklinger",
  },
  {
    name: "Joseph Abebe",
    title: "Investor/Advisor (ex-Slack)",
    src: "/investors/joseph-abebe.jpeg",
    url: "https://twitter.com/josephaabebe",
  },
  {
    name: "Martin Gontovnikas ",
    title: "Co-Founder, HyperGrowth Partners",
    src: "/investors/mgonto.jpeg",
    url: "https://twitter.com/mgonto",
  },
  {
    name: "Jeff Fagnan",
    title: "Founder, Accomplice",
    src: "/investors/jfagnan.webp",
    url: "https://angel.co/p/jfagnan",
  },
  {
    name: "Jake Zeller",
    title: "Partner, AngelList",
    src: "/investors/jake-zeller.jpeg",
    url: "https://twitter.com/jake_zeller",
  },
  {
    name: "Morgan Dioli",
    title: "Partner, Ravix Group",
    src: "/investors/morgan-dioli.jpeg",
    url: "https://www.linkedin.com/in/morgan-dioli-author-cfo",
  },
];
