export const HIGHLIGHT_THEME = {
  hljs: {
    textAlign: "left",
    display: "block",
    overflowX: "auto",
    fontSize: "0.84rem",
  },
  "hljs-subst": {
    color: "#444",
  },
  "hljs-comment": {
    color: "#888",
  },
  "hljs-keyword": {
    color: "#FFEFBD",
  },
  "hljs-attribute": {},
  "hljs-selector-tag": {},
  "hljs-meta-keyword": {},
  "hljs-doctag": {},
  "hljs-name": {},
  "hljs-type": {},
  "hljs-string": {
    color: "#00E9A3",
  },
  "hljs-number": {},
  "hljs-selector-id": {},
  "hljs-selector-class": {},
  "hljs-quote": {},
  "hljs-template-tag": {},
  "hljs-deletion": {},
  "hljs-title": {},
  "hljs-section": {},
  "hljs-regexp": {},
  "hljs-symbol": {},
  "hljs-variable": {},
  "hljs-template-variable": {},
  "hljs-link": {},
  "hljs-selector-attr": {},
  "hljs-selector-pseudo": {},
  "hljs-literal": {},
  "hljs-built_in": {},
  "hljs-bullet": {},
  "hljs-code": {},
  "hljs-addition": {},
  "hljs-meta": {},
  "hljs-meta-string": {},
  "hljs-emphasis": {},
  "hljs-strong": {},
};
